### ISSUE TITLE
Clear Command leads to invalid Description  

### ISSUE THREAD

**Issue by fischejo** [argos-research/genode-Taskloader#4]
Betrifft nur den `push_profile` Branch! Mit dem `1608` Branch konnte ich das nicht beobachten.

Wenn man vor dem Senden der TaskSet Description noch ein
`clear` schickt, dann gibt es Probleme beim Parsen der TaskSet Description.

```
[init -> taskloader] Parsing XML file:
[init -> taskloader] �MQ
[init -> taskloader] Error: Uncaught exception of type 'Genode::Xml_attribute::Invalid_syntax'
[init -> taskloader] Warning: abort called - thread: ep
```

Das sieht man mit nc und hexdump auch ganz schön:

```
00000000  e6 0d 00 00 e5 0d 00 00  27 01 00 00 3c 74 61 73  |........'...<tas|
00000010  6b 73 65 74 3e 0a 09 3c  70 65 72 69 6f 64 69 63  |kset>..<periodic|
00000020  74 61 73 6b 3e 0a 09 09  3c 6f 66 66 73 65 74 3e  |task>...<offset>|
00000030  30 3c 2f 6f 66 66 73 65  74 3e 0a 09 09 3c 69 64  |0</offset>...<id|
00000040  3e 32 3c 2f 69 64 3e 0a  09 09 3c 70 65 72 69 6f  |>2</id>...<perio|
00000050  64 3e 30 3c 2f 70 65 72  69 6f 64 3e 0a 09 09 3c  |d>0</period>...<|
00000060  63 6f 6e 66 69 67 3e 0a  09 09 09 3c 61 72 67 31  |config>....<arg1|
00000070  3e 31 32 36 35 34 36 3c  2f 61 72 67 31 3e 0a 09  |>126546</arg1>..|
00000080  09 3c 2f 63 6f 6e 66 69  67 3e 0a 09 09 3c 71 75  |.</config>...<qu|
00000090  6f 74 61 3e 31 4d 3c 2f  71 75 6f 74 61 3e 0a 09  |ota>1M</quota>..|
000000a0  09 3c 70 72 69 6f 72 69  74 79 3e 30 3c 2f 70 72  |.<priority>0</pr|
000000b0  69 6f 72 69 74 79 3e 0a  09 09 3c 65 78 65 63 75  |iority>...<execu|
000000c0  74 69 6f 6e 74 69 6d 65  3e 39 39 39 39 39 39 39  |tiontime>9999999|
000000d0  39 39 39 39 39 3c 2f 65  78 65 63 75 74 69 6f 6e  |99999</execution|
000000e0  74 69 6d 65 3e 0a 09 09  3c 70 6b 67 3e 68 65 79  |time>...<pkg>hey|
000000f0  3c 2f 70 6b 67 3e 0a 09  09 3c 63 72 69 74 69 63  |</pkg>...<critic|
00000100  61 6c 74 69 6d 65 3e 30  3c 2f 63 72 69 74 69 63  |altime>0</critic|
00000110  61 6c 74 69 6d 65 3e 0a  09 3c 2f 70 65 72 69 6f  |altime>..</perio|
00000120  64 69 63 74 61 73 6b 3e  0a 3c 2f 74 61 73 6b 73  |dictask>.</tasks|
00000130  65 74 3e 1e f1 e5 0d 01  00 00 00                 |et>........|
0000013b
```

Mit den ersten 4 Byte `e6 0d 00 00` (Magic-Number von clear) kommt er nicht klar. 

Wird zwischen dem Senden des Clear Befehls und der Description eine Pause eingelegt, so wird die Description erfolgreich geparsed, jedoch tritt anschließend beim Senden der Binary ein Fehler auf:
```
[init -> taskloader] virtual Genode::Ram_dataspace_capability Taskloader_session_component::binary_ds(Genode::Ram_dataspace_capability, size_t): Reserving 0 bytes for binary �MQ
```
Dabei stimmt die reservierte Anzahl an Bytes und der Name der Binary nicht.

**Comment by BugUser0815** [comment]
I will take a look at it tomorrow morning.

**Comment by BugUser0815** [comment]
Indeed there was a problem if "clear" was sent before "send_descs".
This problem is solved with commit 2ea17e0c2e5808c430713d5b5e6f9efba0886fa9 of dom0-HW branch networker_thread.
Nevertheless I was able to trace your specific problem which occurs if a profile push is held on the network stack once a "GO_SEND" is expected after the task description was sent.
The toolchain-host python scripts then exits with error:
"Invalid answer received, aborting: 150"
150 is the size of the profile push.
"[init -> dom0-HW] Sending profile data of size 150"
