### ISSUE TITLE
`deadline`-parameter freezes system

### ISSUE THREAD

**Issue by fischejo** [argos-research/genode-Taskloader#6]
Any value of deadline greater than 0 freezes the system. It does react to Ping requests, too.

Used taskset:
```
<taskset>
    <periodictask>
        <criticaltime>1000</criticaltime>
        <quota>1M</quota>
        <period>0</period>
        <numberofjobs>0</numberofjobs>
        <pkg>hey</pkg>
        <executiontime>1000</executiontime>
        <priority>10</priority>
        <deadline>2000</deadline>
        <config></config>
        <id>0</id>
    </periodictask>
</taskset>
```

Log:
```
[init -> dom0-HW] Got binary 'hey' of size 44372.
[init -> dom0-HW] void Dom0_server::Dom0_server::serve(): Done SEND_BINARIES. Took: 597
[init -> dom0-HW] void Dom0_server::Dom0_server::Child_starter_thread::do_start(int): Starting tasks.
[init -> taskloader] Starting 1 task.
[init -> taskloader] Starting task 00.hey with quota 1048576 and priority 52 in iteration 1
[init] Warning: priority band too small, losing least-significant priority bits

```

**Comment by BugUser0815** [comment]
This taskset makes no sense.
Our versions of Genode and Fiasco.OC provide two scheduling policies. Fixed_Priority and Earliest_Deadline_First. If you provide both values for a task, Genode should prefer EDF.
In your case Genode obviously tries to start the task as fp, which is not correct.
Consequently you should not do what you did there, even if Genode is not doing what it should do.
I will investigate what Genode is doing there exactly.
